services:
  - type: web
    name: smartcampus-docker
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /_stcore/health
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-3.5-flash-lite
      - key: PLANET_API_KEY
        sync: false
      - key: PLANET_MOSAIC_ID
        sync: false
